### ISSUE TITLE
Does not render colors anymore (possibly?).

### ISSUE THREAD

**Issue by Lurtroxx** [utkarshdubey/react-spline#10]
I have rendered my spline.design view using the react spline npm package within my react site, it does not render the colors, only the lighting effects. I tested this on another spline.design default scene and it resulted in this: 
![download](https://user-images.githubusercontent.com/32040179/119560611-fd565f80-bd58-11eb-9b59-3e74f67eacee.png)

This was tested on a fresh NPX Create-React-App using yarn. 

I receive the following errors in the console. 
![Screenshot (286)](https://user-images.githubusercontent.com/32040179/119560969-72299980-bd59-11eb-805a-ae71ced3b538.png)

**Comment by utkarshdubey** [comment]
Hi! Can you maybe reproduce your project on https://codesandbox.io/.

**Comment by Lurtroxx** [comment]
> Hi! Can you maybe reproduce your project on https://codesandbox.io/.

I have not been able to reproduce a project in codesandbox.io, this is very difficult as it is not allowing me to upload a repo. As far as the problem that is present, I am using Create-React-App and NPM Install react-spline, the spline scene I am using is from their default scenes, I have tried importing the JSON from a JS file and exported const, but that did not help.

**Comment by Lurtroxx** [comment]
update:
I am getting this error from any scene I import. I am importing now to your Example folder TSX Project. The modules you currently have in there (1, 2, 3) are all working, when I replace the data in export scene with my scene data, it gives me this error: 
![Screenshot (289)](https://user-images.githubusercontent.com/32040179/119579151-b1b0af80-bd72-11eb-97f7-76684091cdf2.png)

**Comment by utkarshdubey** [comment]
Can you provide more information on your workspace and the version you're using for the library?

**Comment by Lurtroxx** [comment]
Yes, sorry for the delay I was having dinner! I installed your Examples
folder on your react-spline and it does indeed work when I run it locally
in my browser. I used the react-spline wrapper to render a scene I created
in spline within my website, it resulted in the following image. It has no
color, that blue color is environment lighting.
[image: Screenshot (300).png]

I additionally used a scene from splines provided examples within a
Create-React-App application, and the result is the same as on my personal
scene, no color on any objects. The image is as follows.

[image: Screenshot (301).png]

**Comment by Lurtroxx** [comment]
This is what the scene is supposed to look like on the first image, except
the first image does have a white background, I used spline to change it to
black to show a friend, but this is just an example of the color!![image:
Screenshot (303).png]
!

**Comment by utkarshdubey** [comment]
Hi! Your images are not visible. Also, I'll try hosting a codesandbox and testing the library.

**Comment by Lurtroxx** [comment]
I think in the reply email you must click the message and it will expand, I
sent 2 images within that message!

**Comment by utkarshdubey** [comment]
![image](https://user-images.githubusercontent.com/29272078/119918857-d5e4da00-bf86-11eb-8762-1db8e63cd32d.png)
Ummm nope.

**Comment by Lurtroxx** [comment]
hmmm very strange, ill try to resend.

**Comment by utkarshdubey** [comment]
Wouldn't work, I can only help you once you maybe host your code somewhere and I can have a look at it.

**Comment by Lurtroxx** [comment]
I'll make a repo and give you a link!

**Comment by utkarshdubey** [comment]
Yeah, that'd be helpful.

**Comment by Lurtroxx** [comment]
Were you able to find out more information on this from the repo I sent you, or did it not reproduce the same thing.

**Comment by utkarshdubey** [comment]
Hi! I've not been able to find the time to reproduce the repository's contents.  I did now, and it seems like the colors do not seem to work for real. This is most probably a Spline runtime update that changed things up a bit, I'm working on a fix for the same.

**Comment by ENRICO1834** [comment]
Same problem here, waiting for ur fix!

**Comment by utkarshdubey** [comment]
@Lurtroxx @ENRICO1834 This should be fixed now.
