### ISSUE TITLE
Cannot read property 'SPE_textures_uuid_map' of undefined

### ISSUE THREAD

**Issue by shanematthewkelly** [utkarshdubey/react-spline#12]
Hey! I think someone may have brought this issue up before, but the runtime seems to be currently incompatible with this wrapper library. As of right now, it seems as though this library only accepts GLFT loading when rendering out the scene.

The JSON in this example works and renders: https://github.com/utkarshdubey/react-spline/blob/main/example/src/scene.js

But anything else does not work, the JSON seems to be very different now when exporting scene.json from the URL. Currently I cannot use this library at all until it is compatible 😔

<img width="205" alt="issue" src="https://user-images.githubusercontent.com/55448861/124325193-2c43ca80-db7c-11eb-81d8-3c403ec1981e.PNG">

<img width="326" alt="issue2" src="https://user-images.githubusercontent.com/55448861/124325200-31087e80-db7c-11eb-88d6-20548ea0bbc9.PNG">

#11

**Comment by utkarshdubey** [comment]
This should be fixed now @shanematthewkelly.

**Comment by shanematthewkelly** [comment]
@utkarshdubey it works great now. 🙂 Thanks! Great package by the way.

**Comment by utkarshdubey** [comment]
col
