### ISSUE TITLE
Endless warn-logging by three.js

### ISSUE THREAD

**Issue by flaming-codes** [utkarshdubey/react-spline#13]
Hi and thanks for this neat library, using it worked very well! Only issue I have is that three.js completely spams the log with always the same warning:

<img width="2166" alt="Bildschirmfoto 2021-07-16 um 20 00 10" src="https://user-images.githubusercontent.com/11635736/125990045-e9e473a5-f738-48c2-8cec-75d38ab362a6.png">

Sadly I don't have any experience with three.js, but if you want I can still work on a PR to fix it.

**Comment by utkarshdubey** [comment]
@flaming-codes I just added a quick workaround that removed duplicate warnings from the console. If this hinders your development experience, feel free to reopen this issue or reach out to me.
