### ISSUE TITLE
Deprecate package in favor of official package 

### ISSUE THREAD

**Issue by Dueen** [utkarshdubey/react-spline#21]
The Spline team has released an official package for Spline, so it might be useful to deprecate this package and instruct users to use the official package. This will also avoid confusion for those that are looking for the official package.
[@splinetool/react-spline](https://www.npmjs.com/package/@splinetool/react-spline)

Appreciate the effort that went into building this!

**Comment by utkarshdubey** [comment]
Definitely, thanks!
