### ISSUE TITLE
Facing a error when using the lib with typescript + nextJS

### ISSUE THREAD

**Issue by jpsant** [utkarshdubey/react-spline#5]
Hi, i'm trying to use this lib in my personal project (which i use React with Typescript and Next Js) and i'm getting the following error:

##
![error](https://i.ibb.co/6HhfF29/Screenshot-from-2021-04-03-16-51-36.png)

This is the log from my terminal:
```terminal
import * as three from 'three';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

And this is my tsconfig.json file:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~src/*": ["./src/*"],
      "~components/*": ["./src/components/*"],
      "~assets/*": ["./src/assets/*"],
      "~animations/*": ["./src/assets/animations/*"],
      "~atoms/*": ["./src/components/atoms/*"],
      "~molecules/*": ["./src/components/molecules/*"],
      "~organisms/*": ["./src/components/organisms/*"],
      "~templates/*": ["./src/components/templates/*"],
      "~sections/*": ["./src/components/templates/sections/*"],
      "~dividers/*": ["./src/components/atoms/dividers/*"],
      "~pages/*": ["./src/pages/*"]
    },
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "noImplicitAny": false,
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "custom.d.ts"],
  "exclude": ["node_modules", "build"]
}
```

**Comment by Hydrophobefireman** [comment]
@utkarshdubey  replace imports with nodejs require() calls

**Comment by jpsant** [comment]
Finally I've managed to render the scenes from the example, Thanks for the Help! But now i'm facing another problem. When i try to import a design that I've created on Spline i'm getting this error:
##

![src](https://i.ibb.co/mHJ4GgP/Screenshot-from-2021-04-03-19-07-08.png)

**Comment by Hydrophobefireman** [comment]
Did spline release a new runtime?

@utkarshdubey  can you check for that?

**Comment by utkarshdubey** [comment]
Hi @jpsant,
Sorry for the _very_ late reply, I suppose this has something to do with your exported scene as well. If you still have these files, do you mind sharing more information on the context?

**Comment by utkarshdubey** [comment]
Update @jpsant, Spline did update their runtime and I'm writing the portable version for that now.

**Comment by utkarshdubey** [comment]
Update @jpsant, the error should be fixed by now, apologies for the delayed actions.

**Comment by jpsant** [comment]
No problem! Thanks for the support ❤️
