### ISSUE TITLE
Getting error "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by fatihcandev** [utkarshdubey/react-spline#7]
Hi. Thanks for the library. It's my first time using it and I just got the error below.

[The sandbox
](https://codesandbox.io/s/boring-breeze-gk1ff?file=/src/App.js)

![image](https://user-images.githubusercontent.com/54099904/115842843-e6a1ad80-a426-11eb-8037-f33dd2be87ed.png)

**Comment by utkarshdubey** [comment]
Hey @fatihcandev,
So I did a bit of digging and it seems to me they have changed the original Spline runtime. I'll have to rewrite the library to make it compatible with newer Spline models. As of right now, I don't think we can do much here.

**Comment by fatihcandev** [comment]
> Hey @fatihcandev,
> So I did a bit of digging and it seems to me they have changed the original Spline runtime. I'll have to rewrite the library to make it compatible with newer Spline models. As of right now, I don't think we can do much here.

Cool, thanks a lot 👍🏼

**Comment by utkarshdubey** [comment]
Hey @fatihcandev,
The library should be working now, install the latest version ``react-spline@1.1``
